# Test configuration to trigger LLM endpoint error
# This config uses an invalid model name to test error handling

env_config:
  game_name: "matrix_rps"
  episodes: 1
  max_turns: 10
  random_seed: 42

agents:
  player_0:
    type: llm
    model: "invalid_test_model"  # This will trigger an error
  player_1:
    type: random

mode: llm_vs_random
