# Available LiteLLM models from various providers
# These models are accessible via API-based inference

models:
  # OpenAI models
  - litellm_gpt-3.5-turbo
  - litellm_gpt-4
  - litellm_gpt-4-turbo
  - litellm_gpt-o4-mini
  - litellm_gpt-5
  - litellm_gpt-5-mini

  # Gemini models

  # Groq models (fast inference)
  # https://docs.litellm.ai/docs/providers/groq
  - litellm_groq/llama-3.1-8b-instant
  - litellm_groq/llama-3.1-70b-versatile
  - litellm_groq/gemma2-9b-it
  # Note: Qwen and Kimi models also available via Fireworks AI below

  # Together AI models
  # https://docs.litellm.ai/docs/providers/togetherai
  - litellm_together_ai/meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo
  - litellm_together_ai/meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo
  - litellm_together_ai/mistralai/Mixtral-8x7B-Instruct-v0.1

  # Fireworks AI models
#  https://app.fireworks.ai/models
  - litellm_fireworks_ai/accounts/fireworks/models/llama-v3-8b-instruct
  - litellm_fireworks_ai/accounts/fireworks/models/llama-v3-70b-instruct
  - litellm_fireworks_ai/accounts/fireworks/models/qwen3-235b-a22b-thinking-2507
  - litellm_fireworks_ai/accounts/fireworks/models/glm-4p5-air
  - litellm_fireworks_ai/accounts/fireworks/models/kimi-k2-instruct
